apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: demoapp
  namespace: demo
spec:
  releaseName: demo-app
  chart:
    spec:
      chart: ./charts
      sourceRef:
        kind: GitRepository
        name: demo-app
  interval: 10m
  values:
    replicaCount: 1