apiVersion: source.toolkit.fluxcd.io/v1
kind: GitRepository
metadata:
  name: demo-app
  namespace: demo
spec:
  interval: 10m
  url: https://github.com/YueLiRex/k8s-fluxcd-webhook-demoapp
  ref:
    branch: "main"